package model.entity;

import java.util.Map;

import model.services.AppModuleImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCDataControl;
import oracle.adf.share.ADFContext;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 24 20:02:02 BDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCourierInformationHeaderEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        DocNo {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getDocNo();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setDocNo((Number)value);
            }
        }
        ,
        AwbId {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getAwbId();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setAwbId((String)value);
            }
        }
        ,
        CourierName {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCourierName();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCourierName((String)value);
            }
        }
        ,
        ImportExport {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getImportExport();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setImportExport((String)value);
            }
        }
        ,
        CourierDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCourierDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCourierDate((Date)value);
            }
        }
        ,
        Buyer {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getBuyer();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        DevSampleBulk {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getDevSampleBulk();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setDevSampleBulk((String)value);
            }
        }
        ,
        Unit {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getUnit();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setUnit((String)value);
            }
        }
        ,
        SenderUnit {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getSenderUnit();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setSenderUnit((String)value);
            }
        }
        ,
        DeliveryLocation {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getDeliveryLocation();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setDeliveryLocation((String)value);
            }
        }
        ,
        UserName {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getUserName();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setUserName((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        StyleNumber {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getStyleNumber();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setStyleNumber((String)value);
            }
        }
        ,
        BpoNumber {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getBpoNumber();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setBpoNumber((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        Qty {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getQty();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setQty((Number)value);
            }
        }
        ,
        DocRcvdDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getDocRcvdDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setDocRcvdDate((Date)value);
            }
        }
        ,
        ExpectedDeliveryDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getExpectedDeliveryDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setExpectedDeliveryDate((Date)value);
            }
        }
        ,
        ActualDeliveryDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getActualDeliveryDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setActualDeliveryDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        SampleDocNo {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getSampleDocNo();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setSampleDocNo((Number)value);
            }
        }
        ,
        VersionNo {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        RespId {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getRespId();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setRespId((Number)value);
            }
        }
        ,
        UserId {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getUserId();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setUserId((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        Uom {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getUom();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        KnowStyle {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getKnowStyle();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setKnowStyle((String)value);
            }
        }
        ,
        ConcigneeUnit {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getConcigneeUnit();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setConcigneeUnit((String)value);
            }
        }
        ,
        PayeeUnit {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getPayeeUnit();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setPayeeUnit((String)value);
            }
        }
        ,
        SupplierCountry {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getSupplierCountry();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setSupplierCountry((String)value);
            }
        }
        ,
        ValuePrice {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getValuePrice();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setValuePrice((Number)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        InvoiceDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getInvoiceDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setInvoiceDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        Weight {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getWeight();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setWeight((Number)value);
            }
        }
        ,
        WeightType {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getWeightType();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setWeightType((String)value);
            }
        }
        ,
        PackageQty {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getPackageQty();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setPackageQty((Number)value);
            }
        }
        ,
        Item {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getItem();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        UdNo {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getUdNo();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setUdNo((String)value);
            }
        }
        ,
        ExportLcNo {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getExportLcNo();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setExportLcNo((String)value);
            }
        }
        ,
        CnfAgentName {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCnfAgentName();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCnfAgentName((String)value);
            }
        }
        ,
        DocHandoverDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getDocHandoverDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setDocHandoverDate((Date)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setDeliveryDate((Date)value);
            }
        }
        ,
        CompletionStatusCommercial {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCompletionStatusCommercial();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCompletionStatusCommercial((String)value);
            }
        }
        ,
        CompletionStatusMerchant {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getCompletionStatusMerchant();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setCompletionStatusMerchant((String)value);
            }
        }
        ,
        ActualCreatorName {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getActualCreatorName();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setActualCreatorName((String)value);
            }
        }
        ,
        MnjCourierInformationLineEO {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getMnjCourierInformationLineEO();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjCourierInformationLine2EO {
            public Object get(MnjCourierInformationHeaderEOImpl obj) {
                return obj.getMnjCourierInformationLine2EO();
            }

            public void put(MnjCourierInformationHeaderEOImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjCourierInformationHeaderEOImpl object);

        public abstract void put(MnjCourierInformationHeaderEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int DOCNO = AttributesEnum.DocNo.index();
    public static final int AWBID = AttributesEnum.AwbId.index();
    public static final int COURIERNAME = AttributesEnum.CourierName.index();
    public static final int IMPORTEXPORT = AttributesEnum.ImportExport.index();
    public static final int COURIERDATE = AttributesEnum.CourierDate.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int DEVSAMPLEBULK = AttributesEnum.DevSampleBulk.index();
    public static final int UNIT = AttributesEnum.Unit.index();
    public static final int SENDERUNIT = AttributesEnum.SenderUnit.index();
    public static final int DELIVERYLOCATION = AttributesEnum.DeliveryLocation.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int STYLENUMBER = AttributesEnum.StyleNumber.index();
    public static final int BPONUMBER = AttributesEnum.BpoNumber.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int DOCRCVDDATE = AttributesEnum.DocRcvdDate.index();
    public static final int EXPECTEDDELIVERYDATE = AttributesEnum.ExpectedDeliveryDate.index();
    public static final int ACTUALDELIVERYDATE = AttributesEnum.ActualDeliveryDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int SAMPLEDOCNO = AttributesEnum.SampleDocNo.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int KNOWSTYLE = AttributesEnum.KnowStyle.index();
    public static final int CONCIGNEEUNIT = AttributesEnum.ConcigneeUnit.index();
    public static final int PAYEEUNIT = AttributesEnum.PayeeUnit.index();
    public static final int SUPPLIERCOUNTRY = AttributesEnum.SupplierCountry.index();
    public static final int VALUEPRICE = AttributesEnum.ValuePrice.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int WEIGHT = AttributesEnum.Weight.index();
    public static final int WEIGHTTYPE = AttributesEnum.WeightType.index();
    public static final int PACKAGEQTY = AttributesEnum.PackageQty.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int UDNO = AttributesEnum.UdNo.index();
    public static final int EXPORTLCNO = AttributesEnum.ExportLcNo.index();
    public static final int CNFAGENTNAME = AttributesEnum.CnfAgentName.index();
    public static final int DOCHANDOVERDATE = AttributesEnum.DocHandoverDate.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int COMPLETIONSTATUSCOMMERCIAL = AttributesEnum.CompletionStatusCommercial.index();
    public static final int COMPLETIONSTATUSMERCHANT = AttributesEnum.CompletionStatusMerchant.index();
    public static final int ACTUALCREATORNAME = AttributesEnum.ActualCreatorName.index();
    public static final int MNJCOURIERINFORMATIONLINEEO = AttributesEnum.MnjCourierInformationLineEO.index();
    public static final int MNJCOURIERINFORMATIONLINE2EO = AttributesEnum.MnjCourierInformationLine2EO.index();
    private String userName;

    /**
     * This is the default constructor (do not remove).
     */
    public MnjCourierInformationHeaderEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.MnjCourierInformationHeaderEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for DocNo, using the alias name DocNo.
     * @return the DocNo
     */
    public Number getDocNo() {
        return (Number)getAttributeInternal(DOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocNo.
     * @param value value to set the DocNo
     */
    public void setDocNo(Number value) {
        setAttributeInternal(DOCNO, value);
    }

    /**
     * Gets the attribute value for AwbId, using the alias name AwbId.
     * @return the AwbId
     */
    public String getAwbId() {
        return (String)getAttributeInternal(AWBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwbId.
     * @param value value to set the AwbId
     */
    public void setAwbId(String value) {
        setAttributeInternal(AWBID, value);
    }

    /**
     * Gets the attribute value for CourierName, using the alias name CourierName.
     * @return the CourierName
     */
    public String getCourierName() {
        return (String)getAttributeInternal(COURIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CourierName.
     * @param value value to set the CourierName
     */
    public void setCourierName(String value) {
        setAttributeInternal(COURIERNAME, value);
    }

    /**
     * Gets the attribute value for ImportExport, using the alias name ImportExport.
     * @return the ImportExport
     */
    public String getImportExport() {
        return (String)getAttributeInternal(IMPORTEXPORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImportExport.
     * @param value value to set the ImportExport
     */
    public void setImportExport(String value) {
        setAttributeInternal(IMPORTEXPORT, value);
    }

    /**
     * Gets the attribute value for CourierDate, using the alias name CourierDate.
     * @return the CourierDate
     */
    public Date getCourierDate() {
        return (Date)getAttributeInternal(COURIERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CourierDate.
     * @param value value to set the CourierDate
     */
    public void setCourierDate(Date value) {
        setAttributeInternal(COURIERDATE, value);
    }

    /**
     * Gets the attribute value for Buyer, using the alias name Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String)getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Buyer.
     * @param value value to set the Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for DevSampleBulk, using the alias name DevSampleBulk.
     * @return the DevSampleBulk
     */
    public String getDevSampleBulk() {
        return (String)getAttributeInternal(DEVSAMPLEBULK);
    }

    /**
     * Sets <code>value</code> as the attribute value for DevSampleBulk.
     * @param value value to set the DevSampleBulk
     */
    public void setDevSampleBulk(String value) {
        setAttributeInternal(DEVSAMPLEBULK, value);
    }

    /**
     * Gets the attribute value for Unit, using the alias name Unit.
     * @return the Unit
     */
    public String getUnit() {
        return (String)getAttributeInternal(UNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Unit.
     * @param value value to set the Unit
     */
    public void setUnit(String value) {
        setAttributeInternal(UNIT, value);
    }

    /**
     * Gets the attribute value for SenderUnit, using the alias name SenderUnit.
     * @return the SenderUnit
     */
    public String getSenderUnit() {
        return (String)getAttributeInternal(SENDERUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SenderUnit.
     * @param value value to set the SenderUnit
     */
    public void setSenderUnit(String value) {
        setAttributeInternal(SENDERUNIT, value);
    }

    /**
     * Gets the attribute value for DeliveryLocation, using the alias name DeliveryLocation.
     * @return the DeliveryLocation
     */
    public String getDeliveryLocation() {
        return (String)getAttributeInternal(DELIVERYLOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryLocation.
     * @param value value to set the DeliveryLocation
     */
    public void setDeliveryLocation(String value) {
        setAttributeInternal(DELIVERYLOCATION, value);
    }

    /**
     * Gets the attribute value for UserName, using the alias name UserName.
     * @return the UserName
     */
    public String getUserName() {
        return (String)getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserName.
     * @param value value to set the UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for StyleNumber, using the alias name StyleNumber.
     * @return the StyleNumber
     */
    public String getStyleNumber() {
        return (String)getAttributeInternal(STYLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNumber.
     * @param value value to set the StyleNumber
     */
    public void setStyleNumber(String value) {
        setAttributeInternal(STYLENUMBER, value);
    }

    /**
     * Gets the attribute value for BpoNumber, using the alias name BpoNumber.
     * @return the BpoNumber
     */
    public String getBpoNumber() {
        return (String)getAttributeInternal(BPONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNumber.
     * @param value value to set the BpoNumber
     */
    public void setBpoNumber(String value) {
        setAttributeInternal(BPONUMBER, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the Qty
     */
    public Number getQty() {
        return (Number)getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for DocRcvdDate, using the alias name DocRcvdDate.
     * @return the DocRcvdDate
     */
    public Date getDocRcvdDate() {
        return (Date)getAttributeInternal(DOCRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocRcvdDate.
     * @param value value to set the DocRcvdDate
     */
    public void setDocRcvdDate(Date value) {
        setAttributeInternal(DOCRCVDDATE, value);
    }

    /**
     * Gets the attribute value for ExpectedDeliveryDate, using the alias name ExpectedDeliveryDate.
     * @return the ExpectedDeliveryDate
     */
    public Date getExpectedDeliveryDate() {
        return (Date)getAttributeInternal(EXPECTEDDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpectedDeliveryDate.
     * @param value value to set the ExpectedDeliveryDate
     */
    public void setExpectedDeliveryDate(Date value) {
        setAttributeInternal(EXPECTEDDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for ActualDeliveryDate, using the alias name ActualDeliveryDate.
     * @return the ActualDeliveryDate
     */
    public Date getActualDeliveryDate() {
        return (Date)getAttributeInternal(ACTUALDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualDeliveryDate.
     * @param value value to set the ActualDeliveryDate
     */
    public void setActualDeliveryDate(Date value) {
        setAttributeInternal(ACTUALDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for SampleDocNo, using the alias name SampleDocNo.
     * @return the SampleDocNo
     */
    public Number getSampleDocNo() {
        return (Number)getAttributeInternal(SAMPLEDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleDocNo.
     * @param value value to set the SampleDocNo
     */
    public void setSampleDocNo(Number value) {
        setAttributeInternal(SAMPLEDOCNO, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for RespId, using the alias name RespId.
     * @return the RespId
     */
    public Number getRespId() {
        return (Number)getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RespId.
     * @param value value to set the RespId
     */
    public void setRespId(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the UserId
     */
    public Number getUserId() {
        return (Number)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for KnowStyle, using the alias name KnowStyle.
     * @return the KnowStyle
     */
    public String getKnowStyle() {
        return (String)getAttributeInternal(KNOWSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for KnowStyle.
     * @param value value to set the KnowStyle
     */
    public void setKnowStyle(String value) {
        setAttributeInternal(KNOWSTYLE, value);
    }

    /**
     * Gets the attribute value for ConcigneeUnit, using the alias name ConcigneeUnit.
     * @return the ConcigneeUnit
     */
    public String getConcigneeUnit() {
        return (String)getAttributeInternal(CONCIGNEEUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConcigneeUnit.
     * @param value value to set the ConcigneeUnit
     */
    public void setConcigneeUnit(String value) {
        setAttributeInternal(CONCIGNEEUNIT, value);
    }

    /**
     * Gets the attribute value for PayeeUnit, using the alias name PayeeUnit.
     * @return the PayeeUnit
     */
    public String getPayeeUnit() {
        return (String)getAttributeInternal(PAYEEUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PayeeUnit.
     * @param value value to set the PayeeUnit
     */
    public void setPayeeUnit(String value) {
        setAttributeInternal(PAYEEUNIT, value);
    }

    /**
     * Gets the attribute value for SupplierCountry, using the alias name SupplierCountry.
     * @return the SupplierCountry
     */
    public String getSupplierCountry() {
        return (String)getAttributeInternal(SUPPLIERCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierCountry.
     * @param value value to set the SupplierCountry
     */
    public void setSupplierCountry(String value) {
        setAttributeInternal(SUPPLIERCOUNTRY, value);
    }

    /**
     * Gets the attribute value for ValuePrice, using the alias name ValuePrice.
     * @return the ValuePrice
     */
    public Number getValuePrice() {
        return (Number)getAttributeInternal(VALUEPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValuePrice.
     * @param value value to set the ValuePrice
     */
    public void setValuePrice(Number value) {
        setAttributeInternal(VALUEPRICE, value);
    }

    /**
     * Gets the attribute value for InvoiceNo, using the alias name InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String)getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNo.
     * @param value value to set the InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for InvoiceDate, using the alias name InvoiceDate.
     * @return the InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date)getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceDate.
     * @param value value to set the InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for Weight, using the alias name Weight.
     * @return the Weight
     */
    public Number getWeight() {
        return (Number)getAttributeInternal(WEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Weight.
     * @param value value to set the Weight
     */
    public void setWeight(Number value) {
        setAttributeInternal(WEIGHT, value);
    }

    /**
     * Gets the attribute value for WeightType, using the alias name WeightType.
     * @return the WeightType
     */
    public String getWeightType() {
        return (String)getAttributeInternal(WEIGHTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeightType.
     * @param value value to set the WeightType
     */
    public void setWeightType(String value) {
        setAttributeInternal(WEIGHTTYPE, value);
    }

    /**
     * Gets the attribute value for PackageQty, using the alias name PackageQty.
     * @return the PackageQty
     */
    public Number getPackageQty() {
        return (Number)getAttributeInternal(PACKAGEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackageQty.
     * @param value value to set the PackageQty
     */
    public void setPackageQty(Number value) {
        setAttributeInternal(PACKAGEQTY, value);
    }

    /**
     * Gets the attribute value for Item, using the alias name Item.
     * @return the Item
     */
    public String getItem() {
        return (String)getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Item.
     * @param value value to set the Item
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for UdNo, using the alias name UdNo.
     * @return the UdNo
     */
    public String getUdNo() {
        return (String)getAttributeInternal(UDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for UdNo.
     * @param value value to set the UdNo
     */
    public void setUdNo(String value) {
        setAttributeInternal(UDNO, value);
    }

    /**
     * Gets the attribute value for ExportLcNo, using the alias name ExportLcNo.
     * @return the ExportLcNo
     */
    public String getExportLcNo() {
        return (String)getAttributeInternal(EXPORTLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcNo.
     * @param value value to set the ExportLcNo
     */
    public void setExportLcNo(String value) {
        setAttributeInternal(EXPORTLCNO, value);
    }

    /**
     * Gets the attribute value for CnfAgentName, using the alias name CnfAgentName.
     * @return the CnfAgentName
     */
    public String getCnfAgentName() {
        return (String)getAttributeInternal(CNFAGENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnfAgentName.
     * @param value value to set the CnfAgentName
     */
    public void setCnfAgentName(String value) {
        setAttributeInternal(CNFAGENTNAME, value);
    }

    /**
     * Gets the attribute value for DocHandoverDate, using the alias name DocHandoverDate.
     * @return the DocHandoverDate
     */
    public Date getDocHandoverDate() {
        return (Date)getAttributeInternal(DOCHANDOVERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocHandoverDate.
     * @param value value to set the DocHandoverDate
     */
    public void setDocHandoverDate(Date value) {
        setAttributeInternal(DOCHANDOVERDATE, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date)getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for CompletionStatusCommercial, using the alias name CompletionStatusCommercial.
     * @return the CompletionStatusCommercial
     */
    public String getCompletionStatusCommercial() {
        return (String)getAttributeInternal(COMPLETIONSTATUSCOMMERCIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompletionStatusCommercial.
     * @param value value to set the CompletionStatusCommercial
     */
    public void setCompletionStatusCommercial(String value) {
        setAttributeInternal(COMPLETIONSTATUSCOMMERCIAL, value);
    }

    /**
     * Gets the attribute value for CompletionStatusMerchant, using the alias name CompletionStatusMerchant.
     * @return the CompletionStatusMerchant
     */
    public String getCompletionStatusMerchant() {
        return (String)getAttributeInternal(COMPLETIONSTATUSMERCHANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompletionStatusMerchant.
     * @param value value to set the CompletionStatusMerchant
     */
    public void setCompletionStatusMerchant(String value) {
        setAttributeInternal(COMPLETIONSTATUSMERCHANT, value);
    }

    /**
     * Gets the attribute value for ActualCreatorName, using the alias name ActualCreatorName.
     * @return the ActualCreatorName
     */
    public String getActualCreatorName() {
        return (String)getAttributeInternal(ACTUALCREATORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualCreatorName.
     * @param value value to set the ActualCreatorName
     */
    public void setActualCreatorName(String value) {
        setAttributeInternal(ACTUALCREATORNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCourierInformationLineEO() {
        return (RowIterator)getAttributeInternal(MNJCOURIERINFORMATIONLINEEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCourierInformationLine2EO() {
        return (RowIterator)getAttributeInternal(MNJCOURIERINFORMATIONLINE2EO);
    }


    /**
     * @param headerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number headerId) {
        return new Key(new Object[]{headerId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        try {
            super.create(attributeList);
            Map sessionScope = ADFContext.getCurrent().getSessionScope();
            String user = (String)sessionScope.get("userId");
            //                 String user = "6489";
            
            String respId = (String)sessionScope.get("respId");
            //                         String respId = "51318";
            /* Sequence Generation Code of Header by PwC */ 
             
             oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_COURIER_INFORMATION_HEAD_S",getDBTransaction());          
             oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
             setHeaderId(sVal);
             System.out.println("In Header Recently Created Header ID --> " + sVal);
             
//             if (respId.equals("51318")){
//                setImportExport("Import");     
//             }
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
        
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    //    public void lock() {
    //        super.lock();
    //    }
     public void lock() {
        try {
            super.lock();
        } catch (oracle.jbo.RowInconsistentException e) {
            if (e.getErrorCode().equals("25014")) {
                super.lock();
            } else
                throw e;
        }
    }

     /**
      * Custom DML update/insert/delete logic here.
      * @param operation the operation type
      * @param e the transaction event
      */
     protected void doDML(int operation, TransactionEvent e) {
           
                      Map sessionScope = ADFContext.getCurrent().getSessionScope();
                      String user = (String)sessionScope.get("userId");
//                      String user = "6489";
          
                      String respId = (String)sessionScope.get("respId");
//                      String respId = "5555";
           if (DML_INSERT == operation){
            
               try {
                   System.out.println("@In INSERT DODML");
                   System.out.println("operation number: " + operation);
                   
                   setDocNo(new oracle.jbo.domain.Number(getSrNoInt()));
                   setCreationDate((Date)Date.getCurrentDate());
                   
                   System.out.println("Doc No: " +getSrNoInt());
                   
                   setCreatedBy(new oracle.jbo.domain.Number(user));
                   
                   setActualCreatorName(userIdToUserName(user));
                       
                   setRespId(new oracle.jbo.domain.Number(respId));
                   
                  
                  
               } catch (Exception f) {
                   System.out.println(f.getMessage());
               }
           }
           
         if(DML_UPDATE == operation){
             try {
                 System.out.println("@In UPDATE DODML");
                 System.out.println("operation number: " + operation);
                 
                 setLastUpdateDate((Date)Date.getCurrentDate());
                 
                 setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                 
             } catch (Exception f) {
                 System.out.println(f.getMessage());
             }
         }
           super.doDML(operation, e);
     }
     
    public ApplicationModule getAppM() {
        DCBindingContainer bindingContainer =
            (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
        //BindingContext bindingContext = BindingContext.getCurrent();
        DCDataControl dc =
            bindingContainer.findDataControl("AppModuleDataControl"); // Name of application module in datacontrolBinding.cpx
        AppModuleImpl appM = (AppModuleImpl)dc.getDataProvider();
        return appM;
    }
    AppModuleImpl appM = (AppModuleImpl)this.getAppM();
      
     public int getSrNoInt() {
               int srno = 0;
               String stmt = "BEGIN :1 := CUST_MNJ_ONT_PKG.MNJ_COURIER_ENTRY_HEADER_SRNO; end;";
               java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
               try {
                   cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
                   cs.execute();
                   srno = cs.getInt(1);
                   cs.close();
               } catch (Exception e) {
                   e.printStackTrace();
               }
               return srno;
             
         }
     
    private String userIdToUserName(String userId){
        System.out.println("Enter into userIdToUserName method... ");
        ViewObject vo= appM.getAllUserNameLOV1();
        
        RowSetIterator rsit = vo.createRowSetIterator("aa");
        
        while(rsit.hasNext()){
            Row row = rsit.next();
    //                userName = (String)row.getAttribute("UserName");
    //                System.out.println("userName: " + userName);
            if (userId.equals(row.getAttribute("UserId").toString())){
                userName = (String)row.getAttribute("UserName");
                System.out.println("userName: " + userName);
                return userName;
            }
        }
        
        rsit.closeRowSetIterator();
        
        return null;
    }
}
