package model.view;

import model.services.CustomViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 01 16:14:30 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCourierInformationHeaderVOImpl extends CustomViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjCourierInformationHeaderVOImpl() {
    }


}
